### ISSUE TITLE
Issue-[update]: requested changes

### ISSUE THREAD

**Issue by texora** [texora/jobsite#12]
Automated Review Comments
Issues in README.md:
  - (23, 'Line exceeds 80 characters')
Issues in components/Footer.tsx:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
Issues in components/GithubBadge.tsx:
  - (6, 'Line exceeds 80 characters')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in prisma/seed.ts:
  - (3, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in zod/job.ts:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in zod/user.ts:
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')

**Comment by hectris** [comment]
I got it.
