### ISSUE TITLE
Issue-fix: update placeholder text for company salary input in NewJobForm

### ISSUE THREAD

**Issue by texora** [texora/jobsite#22]
Automated Review Comments
Issues in README.md:
  - (12, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
Issues in components/forms/NewJobForm.tsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by hectris** [comment]
I got it.
