### ISSUE TITLE
Issue-adds seeding data in the db logic

### ISSUE THREAD

**Issue by texora** [texora/jobsite#24]
Automated Review Comments
Issues in Dockerfile:
  - (33, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
Issues in components/forms/NewJobForm.tsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in prisma/seed.ts:
  - (4, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (63, 'Hardcoded string found')

**Comment by hectris** [comment]
I got it.
