### ISSUE TITLE
Issue-filter jobs feature created

### ISSUE THREAD

**Issue by texora** [texora/jobsite#36]
Automated Review Comments
Issues in README.md:
  - (15, 'Line exceeds 80 characters')
Issues in actions/job.ts:
  - (7, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
Issues in app/(protected)/jobs/page.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
Issues in components/Sidebar.tsx:
  - (8, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (141, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
Issues in components/ui/slider.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')

**Comment by hectris** [comment]
I got it.
