### ISSUE TITLE
Issue-:sparkles:add mobile nav and fix the overflowing of Navbar

### ISSUE THREAD

**Issue by texora** [texora/jobsite#38]
Automated Review Comments
Issues in actions/job.ts:
  - (6, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
Issues in app/(auth)/layout.tsx:
  - (4, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
Issues in app/(protected)/jobs/layout.tsx:
  - (6, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
Issues in app/(protected)/jobs/page.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
Issues in app/page.tsx:
  - (14, 'Line exceeds 80 characters')
Issues in components/Navbar/MobileNav.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
Issues in components/Navbar/Navbar.tsx:
  - (2, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
Issues in components/Sidebar.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
Issues in components/SiteHeader.tsx:
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
Issues in components/ui/dropdown-menu.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (183, 'Hardcoded string found')
Issues in components/ui/sheet.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (112, 'Line exceeds 80 characters')

**Comment by hectris** [comment]
I got it.
